# Autogenerated wrapper script for libMTIRI2020_jll for x86_64-w64-mingw32-libgfortran3
export libMTIRI2020_00_, libMTIRI2020_1, libMTIRI2020_2, libMTIRI2020_3, libMTIRI2020_4, libMTIRI2020_5, libMTIRI2020_6

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libMTIRI2020")
JLLWrappers.@declare_library_product(libMTIRI2020_00_, "libMTIRI2020_00_.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_1, "libMTIRI2020_1.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_2, "libMTIRI2020_2.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_3, "libMTIRI2020_3.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_4, "libMTIRI2020_4.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_5, "libMTIRI2020_5.dll")
JLLWrappers.@declare_library_product(libMTIRI2020_6, "libMTIRI2020_6.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libMTIRI2020_00_,
        "bin\\libMTIRI2020_00_.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_1,
        "bin\\libMTIRI2020_1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_2,
        "bin\\libMTIRI2020_2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_3,
        "bin\\libMTIRI2020_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_4,
        "bin\\libMTIRI2020_4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_5,
        "bin\\libMTIRI2020_5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMTIRI2020_6,
        "bin\\libMTIRI2020_6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
